version: '3.3'
services:
  # Redmine custom service.
  app:
    build:
      context: ./app
    image: redmine:bkp_app_redmine_5.0.6
    container_name: bkp_redmine_5.0.6
    ports:
      - 80:3000
    volumes:
      - ./app/data/docker_redmine_plugins:/usr/src/redmine/plugins
      - ./app/data/docker_redmine_themes:/usr/src/redmine/public/themes
      - ./app/data/docker_redmine_data:/usr/src/redmine/files
      - ./app/data/docker_redmine_logs:/usr/src/redmine/log
    environment:
      TZ: Europe/Kyiv
      REDMINE_DB_MYSQL: db
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_USERNAME: root
      REDMINE_DB_PASSWORD: root_password
    depends_on:
      - db
    networks:
      - redmine-network
    restart: always
  # MySQL database service
  db:
    build:
      context: ./db
    image: mysql:bkp_db_mysql_5.7
    container_name: bkp_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: redmine
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    volumes:
      - ./db/data/mysql_data:/var/lib/mysql
      - ./db/data/mysql_logs:/var/log/mysql
    networks:
      - redmine-network
    restart: always


networks:
  redmine-network:
    driver: bridge
