version: '3.3'
services:
  # Redmine custom service.
  app:
    build:
      context: ./app
    image: redmine:${REDMINE_IMG_VER}
    container_name: ${REDMINE_IMG_VER}
    ports:
      - 80:3000
    volumes:
      - ./app/data/docker_redmine_plugins:${REDMINE_PLUGINS}
      - ./app/data/docker_redmine_themes:${REDMINE_THEMES}
      - ./app/data/docker_redmine_data:${REDMINE_DATA}
      - ./app/data/docker_redmine_logs:${REDMINE_LOGS}
      # Configuration files
      - ./app/data/docker_redmine_config/configuration.yml:${REDMINE_CONFIG}
      - ./app/data/docker_redmine_config/additional_environment.rb:${REDMINE_LOG_CONFIG}
    environment:
      TZ: Europe/Kyiv
      REDMINE_DB_MYSQL: db
      REDMINE_DB_DATABASE: ${REDMINE_DB_NAME}
      REDMINE_DB_USERNAME: ${REDMINE_DB_USER}
      REDMINE_DB_PASSWORD: ${REDMINE_DB_PASSWORD}
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - redmine-network
    restart: always
  # MySQL database service
  db:
    build:
      context: ./db
    image: mysql:${DB_IMG_VER}
    container_name: bkp_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${REDMINE_DB_PASSWORD}
      MYSQL_DATABASE: ${REDMINE_DB_NAME}
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci", "--explicit_defaults_for_timestamp=true"]
    volumes:
      - ./db/data/mysql_data:${DB_DATA}
      - ./db/data/mysql_logs:${DB_LOGS}
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u $REDMINE_DB_USER --password=$REDMINE_DB_PASSWORD"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - redmine-network
    restart: always


networks:
  redmine-network:
    driver: bridge
