version: '3.3'
services:
  # Redmine custom service.
  app:
    build:
      context: .
    image: redmine:bkp.v1
    container_name: redmine_bkport
    ports:
      - 80:3000
    volumes:
      - ./storage/docker_redmine-plugins:/usr/src/redmine/plugins
      - ./storage/docker_redmine-themes:/usr/src/redmine/public/themes
      - ./storage/docker_redmine-data:/usr/src/redmine/files
    environment:
      REDMINE_DB_MYSQL: redmine
      REDMINE_DB_PASSWORD: redmine_db_password
      REDMINE_DB_ENCODING: utf8
      REDMINE_DB_COLLATION: utf8_general_ci
    depends_on:
      - db
    networks:
      - redmine-network
    restart: always
  # MySQL database service
  db:
    image: mysql:5.7
    container_name: mysql_db_redmine_bkport
    environment:
      MYSQL_ROOT_PASSWORD: redmine_db_password
      MYSQL_DATABASE: redmine
      MYSQL_CHARSET: utf8
      MYSQL_COLLATION: utf8_general_ci
    volumes:
      - ./storage/mysql-data:/var/lib/mysql
    networks:
      - redmine-network
    restart: always


networks:
  redmine-network:
    driver: bridge
