production:
   email_delivery:
     delivery_method: :smtp
     smtp_settings:
       enable_starttls_auto: true
       address: "smtp.gmail.com"
       port: 587
       domain: "smtp.gmail.com"
       authentication: :plain
       user_name: ""
       password: ""



       log_rotate: true
       log_rotate_frequency: daily
       log_rotate_max_age: 30
       log_rotate_size: 100M
       log_rotate_keep: 10
